name: Scrape Sofifa to Database (Simple)

on:
  schedule:
    - cron: '0 2 * * *'  
  workflow_dispatch:     

jobs:
  scrape-and-store:
    runs-on: ubuntu-latest
    timeout-minutes: 360  
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Initialize fresh npm project
        run: |
          npm init -y
          npm install mysql2
          
      - name: Run original scraper
        run: |
          echo "Running original scraper..."
          node full.js
          
      - name: Upload to database
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "Uploading to database..."
          node scripts/upload-to-mysql.js
