name: Scrape Sofifa to Database

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:     # Manual trigger

jobs:
  scrape-and-store:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours for 18k players
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Remove package-lock.json to avoid conflicts
        run: rm -f package-lock.json
          
      - name: Install all dependencies fresh
        run: |
          npm install
          npm install mysql2
          
      - name: Verify installation
        run: |
          echo "Checking installed packages..."
          npm list mysql2
          
      - name: Run scraper and store to database
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "Starting scraper..."
          npm run full
          echo "Scraper completed, uploading to database..."
          node scripts/upload-to-mysql.js
